-- PESSOA (IDs 1..3) - idempotente
MERGE INTO PESSOA (ID_PESSOA, NOME_PESSOA, EMAIL_PESSOA, SENHA_PESSOA, CRACHEID_PESSOA, TIPO_USUARIO)
KEY(ID_PESSOA) VALUES
(1, 'Alice Admin', 'alice.admin@smart.com', '{noop}admin123', 'CR001', 'ADMIN'),
(2, 'Otavio Organizador', 'otavio.organizador@smart.com', '{noop}org123', 'CR002', 'ORGANIZADOR'),
(3, 'Paula Participante', 'paula.participante@smart.com', '{noop}part123', 'CR003', 'PARTICIPANTE');

-- SALA (IDs 1..3)
MERGE INTO SALA (ID_SALA, NOME_SALA, CAPACIDADE_SALA, LOCALIZACAO_SALA, STATUS_SALA)
KEY(ID_SALA) VALUES
(1, 'Sala Azul', 8, 'Bloco A - 1o andar', 'LIVRE'),
(2, 'Sala Verde', 12, 'Bloco B - 2o andar', 'OCUPADA'),
(3, 'Sala Amarela', 6, 'Bloco C - Térreo', 'RESERVADA');

-- REUNIAO (IDs 1..3)
MERGE INTO REUNIAO (
  ID_REUNIAO, DATAHORAINICIO_REUNIAO, DURACAOMINUTOS_REUNIAO, PAUTA_REUNIAO, ATA_REUNIAO, STATUS_REUNIAO,
  ORGANIZADOR_ID, SALA_ID, VERSION
)
KEY(ID_REUNIAO) VALUES
(1, TIMESTAMP '2025-11-07 09:00:00', 60, 'Kickoff do projeto', 'Ata inicial', 'AGENDADA', 2, 1, 0),
(2, TIMESTAMP '2025-11-07 11:00:00', 45, 'Revisão de sprint', 'Ata sprint 12', 'EM_ANDAMENTO', 1, 2, 0),
(3, TIMESTAMP '2025-11-08 15:30:00', 90, 'Planejamento trimestral', 'Ata Q4', 'FINALIZADA', 2, 3, 0);

-- REUNIAO_PARTICIPANTES (JOIN TABLE) - composite key
MERGE INTO REUNIAO_PARTICIPANTES (REUNIAO_ID, PESSOA_ID)
KEY(REUNIAO_ID, PESSOA_ID) VALUES
(1, 1), (1, 3),
(2, 2), (2, 3),
(3, 1), (3, 2), (3, 3);

-- PRESENCA (IDs 1..3)
MERGE INTO PRESENCA (ID_PRESENCA, HORA_ENTRADA, VALIDOPORCRACHA_PRESENCA, PARTICIPANTE_ID, REUNIAO)
KEY(ID_PRESENCA) VALUES
(1, TIMESTAMP '2025-11-07 08:55:00', TRUE, 1, 1),
(2, TIMESTAMP '2025-11-07 11:05:00', FALSE, 3, 2),
(3, TIMESTAMP '2025-11-08 15:25:00', TRUE, 2, 3);

-- TAREFA (IDs 1..3)
MERGE INTO TAREFA (ID_TAREFA, DESCRICAO_TAREFA, PRAZO_TAREFA, CONCLUIDA_TAREFA, STATUS_TAREFA, PRIORIDADE_TAREFA, ID_RESPONSAVEL, ID_REUNIAO)
KEY(ID_TAREFA) VALUES
(1, 'Preparar apresentação', DATE '2025-11-10', FALSE, 'PENDENTE', 'ALTA', 1, 1),
(2, 'Coletar métricas', DATE '2025-11-12', FALSE, 'EM_ANDAMENTO', 'MÉDIA', 3, 2),
(3, 'Fechar ata e enviar', DATE '2025-11-09', TRUE, 'CONCLUIDA', 'BAIXA', 2, 3);

-- NOTIFICACAO (IDs 1..3)
MERGE INTO NOTIFICACAO (ID_NOTIFICACAO, MENSAGEM_NOTIFICACAO, DATAENVIO_NOTIFICACAO, TIPO_NOTIFICACAO, ID_DESTINATARIO)
KEY(ID_NOTIFICACAO) VALUES
(1, 'Sua reunião vai começar em 10 minutos', TIMESTAMP '2025-11-07 08:50:00', 'EMAIL', 1),
(2, 'Você foi adicionado à reunião de revisão', TIMESTAMP '2025-11-07 10:30:00', 'CONSOLE', 3),
(3, 'Tarefa concluída com sucesso', TIMESTAMP '2025-11-08 16:50:00', 'PUSH', 2);

-- Sequências: cria se não existir e posiciona alto para evitar colisão
CREATE SEQUENCE IF NOT EXISTS SQ_PESSOA START WITH 100;
CREATE SEQUENCE IF NOT EXISTS SQ_SALA START WITH 100;
CREATE SEQUENCE IF NOT EXISTS SQ_REUNIAO START WITH 100;
CREATE SEQUENCE IF NOT EXISTS SQ_PRESENCA START WITH 100;
CREATE SEQUENCE IF NOT EXISTS SQ_TAREFA START WITH 100;
CREATE SEQUENCE IF NOT EXISTS SQ_NOTIFICACAO START WITH 100;
ALTER SEQUENCE SQ_PESSOA RESTART WITH 100;
ALTER SEQUENCE SQ_SALA RESTART WITH 100;
ALTER SEQUENCE SQ_REUNIAO RESTART WITH 100;
ALTER SEQUENCE SQ_PRESENCA RESTART WITH 100;
ALTER SEQUENCE SQ_TAREFA RESTART WITH 100;
ALTER SEQUENCE SQ_NOTIFICACAO RESTART WITH 100;
